### ISSUE TITLE
map.invalidateSize() quebra quando tela é grande demais

### ISSUE THREAD

**Issue by tiagofassoni** [biciguia/biciguia-frontend#1]
Quando se aperta o botão para o menu sair, tem um delay de animação. Esse delay é a largura do menu diminuindo até zerar. 

Mas o map.invalidateSize() é chamado antes da animação terminar e ele pega o tamanho errado de tela. Logo, fica um pedaço da tela sem mapa.

**Comment by tiagofassoni** [comment]
O código que gera a transição entre mapa e menu é este:

``` javascript
      $('#menu').animate({width: 'toggle'});
      $('#map').toggle();
      map.invalidateSize(); //So the tile maps load
```

So far, so good. O problema é que em telas grandes o mapa fica com um pedaço sem carregar. CHUTO que o problema seja por causa da animação, que demora mais em telas grandes.

Ou seja, como a animação demora, o map.invalidateSize() é chamado e ele pega um tamanho parcial. Mas preciso investigar.

**Comment by leeohaddad** [comment]
Valeu Tiago!

Isso já tinha ficado claro depois que conseguimos usar o botão de menu (ele
não estava aparecendo porque tinha um submodule que a gente tinha que
baixar e nós não estávamos sabendo)...
Com o botão de menu funcionando no localhost, conseguimos fazer os testes e
entender os issues!

Abraços!

Em 20 de maio de 2015 18:52, Tiago Fassoni notifications@github.com
escreveu:

> O código que gera a transição entre mapa e menu é este:
> 
> ```
>   $('#menu').animate({width: 'toggle'});
>   $('#map').toggle();
>   map.invalidateSize(); //So the tile maps load
> ```
> 
> So far, so good. O problema é que em telas grandes o mapa fica com um
> pedaço sem carregar. CHUTO que o problema seja por causa da animação, que
> demora mais em telas grandes.
> 
> Ou seja, como a animação demora, o map.invalidateSize() é chamado e ele
> pega um tamanho parcial. Mas preciso investigar.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/biciguia/biciguia-frontend/issues/1#issuecomment-104049565
> .

## 

_Leonardo Haddad Carlos_
_Aluno de Ciência da Computação no IME|USP_
_Desenvolvedor na empresa EvoBooks_

**Comment by tiagofassoni** [comment]
Valeu, Leo!

Vou testar isso em casa, pq lá tenho monitor grande o suficiente pra esse bug aparecer. 

Vida Logna e Próspera,
Tiago

**Comment by wwared** [comment]
O problema era esse mesmo que vocês achavam. Aproveitei e consertei outros problemas que aconteciam quando a tela mudava de tamanho e o mapa e/ou menu não apareciam corretamente (por exemplo o fato das regras adicionadas pelo jquery quando toggle() é chamada não serem removidas quando a tela muda de tamanho, diferente das regras de media query que estão em regras_basicas.css).

Acho que seria melhor substituir essa parte do código com algo mais robusto/extensível, pelo menos para o código não ficar uma bagunça horrível na hora de adicionar menus/telas novas.

**Comment by tiagofassoni** [comment]
Valeu! Já testei, funciona. Tô pensando no que fazer nisso, sexta-feira discutimos.
