### ISSUE TITLE
Arquivos .json não aparecem no github

### ISSUE THREAD

**Issue by tiagofassoni** [biciguia/biciguia-frontend#17]
Os overlays são baixados no lib_map.js via uma chamada de $.getJson. O $.getJson tá assumindo que os arquivos sempre ficam na raiz do domínio. Como o github pages deixa tudo em biciguia.github.io**/biciguia-frontend**, quebra tudo.

**Comment by tiagofassoni** [comment]
DUH, o "/" é relativo à raiz do domínio (e nem sei porque tinha o "../" lá). Foi só removê-lo e tudo funcionou.

http://stackoverflow.com/questions/6283000/determining-relative-path-with-jquery

**Comment by tiagofassoni** [comment]
Porque você reabriu?

**Comment by leeohaddad** [comment]
Pessoal, acho que, por padrão, podemos sempre enviar um e-mail/comentário
quando reabrirmos uma feature, pra explicar o motivo do fechamento e evitar
essas confusões!

2015-06-01 20:34 GMT-03:00 Tiago Fassoni notifications@github.com:

> Porque você reabriu?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/biciguia/biciguia-frontend/issues/17#issuecomment-107747030
> .

## 

_Leonardo Haddad Carlos_
_Aluno de Ciência da Computação no IME|USP_
_Desenvolvedor na empresa EvoBooks_
