### ISSUE TITLE
Quando ponto de origem foi escolhido no mapa, a escolha de ponto de destino via caixa de texto fica zoada

### ISSUE THREAD

**Issue by tiagofassoni** [biciguia/biciguia-frontend#20]
Como chegar no bug:

1) Escolha um ponto de partida no mapa.
2) Escolha o ponto de chegada via caixa de texto
3) Veja o seletor de texto descendo para a primeira caixa e não a segunda.

**Comment by leeohaddad** [comment]
Oi Tiago,
Não conseguimos reproduzir o bug. Você pode especificar melhor?

1) O "seletor de texto" ao qual você se refere é o dropdown menu com os endereços retornados pelo geocoder?
Quando a gente faz esse teste, o seletor de texto aparece no local correto: embaixo da segunda caixa...

2) Em que browser você fez esse teste? O erro acontece no layout completo, no layout responsivo ou em ambos?

**Comment by wwared** [comment]
Tiago, só pra confirmar, esse bug ainda existe? Ainda não conseguimos reproduzir aqui

**Comment by wwared** [comment]
Fechando por não ser mais relevante
