### ISSUE TITLE
Quando mostrar rota: tirar os segundos e deixar somente os metros

### ISSUE THREAD

**Issue by tiagofassoni** [biciguia/biciguia-frontend#21]
As rotas são mostradas com os segundos que vai levar cada trecho e com os metros com várias casas decimais de precisão. 

Não precisamos de tanto!

É para tirar os segundos e deixar somente a parte inteira dos metros (com arredondamento ao invés de cortar, pelamordedeus!)

Além disso, humanizar: 1680 metros viram 1,7km. 

(Será que o graphhopper faz isso? Se fizer, por favor, me avisem que mudo as configurações lá e boa)

**Comment by fabiokaspar** [comment]
Não entendemos ao certo se era pra tirar os segudos e deixar apenas os minutos e as horas ou se era pra tirar o tempo de modo geral. Terminamos a issue , deixando o tempo sem os segundos.
