### ISSUE TITLE
Spinner não para de girar!

### ISSUE THREAD

**Issue by tiagofassoni** [biciguia/biciguia-frontend#22]
Ele deveria sumir quando não tá sendo usado.

**Comment by wwared** [comment]
Conseguimos reproduzir no firefox versão 38, mas no chrome e no safari ele para de rodar.

**Comment by wwared** [comment]
Tiago, esse bug já foi consertado? Podemos fechar?

**Comment by wwared** [comment]
Fechando por não ser mais relevante
