### ISSUE TITLE
Quando se pede uma rota em interface responsiva, mapa não centraliza corretamente

### ISSUE THREAD

**Issue by tiagofassoni** [biciguia/biciguia-frontend#23]

**Comment by vonpupp** [comment]
Vc ta testando onde? Celular ou tablet? Se for tablet tem como trazer o dispositivo hj pra a gente entender melhor?

**Comment by tiagofassoni** [comment]
testei isso num celular, mas é só diminuir o tamanho da janela do navegador que a issue aparece.

**Comment by wwared** [comment]
Não conseguimos reproduzir direito, você ainda consegue reproduzir? Fez alguma coisa em específico?

**Comment by wwared** [comment]
Fechando porque acho que não é mais relevante
