### ISSUE TITLE
Mais painéis!

### ISSUE THREAD

**Issue by tiagofassoni** [biciguia/biciguia-frontend#24]
A ideia (que não consegui apresentar para a galera porque a retrospectiva comeu o tempo) é de que as outras interações venham em outros paineis, e os paineis possam ocupar o lugar do painel de rota.

Por exemplo, a parte de rota zoada idealmente ficaria num outro painel que substituiria o painel de escolha de rota.

Da mesma forma, poderíamos ter um painel que fala sobre o projeto.

O comportamento default em tela grande é fazer um stack de paineis, mais ou menos como está na figura. No mobile, só ficaria um por vez.
![capture d ecran 2015-05-29 a 5 12 02 pm](https://cloud.githubusercontent.com/assets/291019/7891784/dcdfc818-0625-11e5-887b-8e9067c8e61e.png)

**Comment by tiagofassoni** [comment]
Penso que a melhor forma de fazer esse treco funcionar decentemente (sem pirar com um milhão de interações de jQuery) seria fazer um estado global e passar para o React.

@santagada , sugestões?

**Comment by santagada** [comment]
Quando a coisa complica o pessoal do React gosta de usar algo chamado Flux para gerenciar as interações e o contexto. Mas pra esse app eu faria com uns globais sim.
