### ISSUE TITLE
Se usuário inputa latitude e longitude como origem e destino, o frontend aceita

### ISSUE THREAD

**Issue by tiagofassoni** [biciguia/biciguia-frontend#25]
(isso é importante pra caramba para motivos de debugar rotas)

**Comment by leeohaddad** [comment]
A função latLonInput, executada no keyUpHandler dos campos de origem e destino, checa se o texto representa um ponto de latitude e longitude e, em caso positivo, configura o marker com o ponto definido e impede que a busca do Geocoder seja feita.
