### ISSUE TITLE
Painéis tem bugs de responsividade

### ISSUE THREAD

**Issue by ricardoteles** [biciguia/biciguia-frontend#29]
Envolve um pouco de investigação. As coisas deveriam ter sido feitas com media queries no CSS, mas para virar "um app", estao como javascript. O que fazer? Adicionar event listeners no resize?

**Comment by tiagofassoni** [comment]
Consegui resolver usando classes tipo menu-active e menu-inactive. Estou debugando e a Internet de casa caiu (estou comentando pelo 3g), então amanhã termino
