### ISSUE TITLE
Ver se funciona com Mapbox-gl

### ISSUE THREAD

**Issue by tiagofassoni** [biciguia/biciguia-frontend#3]
E aí, de brinde, param de encher o saco que "o scroll do phonegap não é rápido o bastante"

**Comment by tiagofassoni** [comment]
Tem um branch com essa feature que vou pushar daqui a pouco.

Infelizmente a aceleração de OpenGL ainda é bem tosqueira em celulares, então embora a velocidade seja tão boa ou melhor quanto na web, no mobile é uma tristeza generalizada. No meu Moto G 2a edição, o único navegador que aceitou uma velocidade ok nisso é o Opera Mobile...

Acho que em alguns meses veremos melhora nisso aí.

**Comment by tiagofassoni** [comment]
@santagada , olha aí, você que mexe com phonegap mobile...

**Comment by santagada** [comment]
Tem q testar no crosswalk e no iOS pra ver como fica. Daria pra encapsular o nativo dele como um plugin pro cordova.

**Comment by tiagofassoni** [comment]
É que o crosswalk usa a última versão do chrome. Testei com o chrome beta e
tava lento pra caramba. Tento com o crosswalk só para tirar a prova quando
chegar em casa.

Mas acho que o jeito seria o encapsulamento e dois builds, um de web e
outro de cordova.

**Comment by tiagofassoni** [comment]
Bom, mandei uma issue no mapbox-gl-js e... o pessoal da Mapbox tem o desenvolvedor do Leaflet trabalhando nisso (foi ele que respondeu minha issue).

Então, véi, na boa, eles resolvem isso em alguns meses.
