### ISSUE TITLE
Diminuir os JSON de dados espaciais 

### ISSUE THREAD

**Issue by tiagofassoni** [biciguia/biciguia-frontend#31]
Eles vêm com um monte de metadados meio inúteis. E aí, mesmo com gzip, ficam arquivos grandes

**Comment by wwared** [comment]
Seria bom olhar o commit qualquer coisa, mas criamos um arquivo [minify.js](https://github.com/biciguia/biciguia-frontend/blob/develop/assets/overlays-min/minify.js) que roda usando o node para 'minificar' os jsons. Ele só remove os dados que a gente não usa.

Nota (importante!): As descrições dos markers está sendo gerada por este arquivo, então no futuro, para atualizar ou descrições ou os dados espaciais, será preciso rodar o minify.js novamente.

Os resultados:
Minificados:

> 4,0K   overlays-min/ambulatorios_de_especialidades.json
> 28K    overlays-min/bibliotecas.json
> 8,0K   overlays-min/bosques_e_pontos_de_leitura.json
> 8,0K   overlays-min/hospitais.json
> 4,0K   overlays-min/museus.json
> 8,0K   overlays-min/pronto-socorros.json
> 104K   overlays-min/ubs.json
> 164K   total

Originais:

> 40K    overlays-original/ambulatorios_de_especialidades.json
> 216K   overlays-original/bibliotecas.json
> 64K    overlays-original/bosques_e_pontos_de_leitura.json
> 44K    overlays-original/hospitais.json
> 28K    overlays-original/museus.json
> 64K    overlays-original/pronto-socorros.json
> 1008K  overlays-original/ubs.json
> 1,5M   total
