### ISSUE TITLE
Não mostrar lista de endereços se a caixa de endereço não está em foco

### ISSUE THREAD

**Issue by brunoendo** [biciguia/biciguia-frontend#34]
Atualmente está muito confuso quando você digita dois endereços rapidamente, ele mostra as lista de endereços depois de um delay. Seria bom não mostrar a lista se o usuário clicar fora da caixa de endereço, para que não haja confusão.

**Comment by wwared** [comment]
Seria bom também mostrar a lista de endereços novamente se o usuário clicar na caixa de endereço depois.
