### ISSUE TITLE
Os ícones novos quebraram o context menu

### ISSUE THREAD

**Issue by wwared** [biciguia/biciguia-frontend#38]
Quando consertamos a issue #8, o context menu parou de funcionar, e dois testes foram quebrados.

**Comment by vonpupp** [comment]
Done! Era um carangeijo psicodelico. O teste chamava uma funcao passando um parametro "key" como undefined... verifiquei isso com um if e resolveu. Nao faco ideia do porque uma funcao foi chamada pelo teste com um undefined
