### ISSUE TITLE
Geocoder só com resultados da bounding box de São Paulo

### ISSUE THREAD

**Issue by tiagofassoni** [biciguia/biciguia-frontend#7]
O trampo com o geocoder tá muito bom, muito rápido. Mas como eu não estaria escrevendo isto aqui se não tivesse problemas....:

O geocoder do OSM, o Nominatim, não filtra resultados por cidade, nem mandando. Então sobrou para a gente fazer isso. 

A idéia é usar o turf.js para ver quais resultados do geocoder estão dentro da bounding box - e jogar fora o resto.

**Comment by tiagofassoni** [comment]
Uso estas coordenadas como bounding box:

```
bounding-box left=-47.357 top=-23.125 bottom=-24.317 right=-45.863
```

**Comment by santagada** [comment]
Ver se o resultado esta dentro de uma caixa é um if com 4 clausulas né? Não sei se precisa de biblioteca pra isso.

**Comment by tiagofassoni** [comment]
DUH, verdade. (Ou não, viu, acho que vale ao menos olhar o código do
turf.js, essas coisas de geodesia tem suas especificidades.... ou tô sendo
overzealous, sei lá)

**Comment by santagada** [comment]
Um retângulo e um retângulo na superfície de um geodo não são a mesma coisa, mas a diferença é tão pequena e irrelevante se vc pensar que SP não é um retângulo também.

Mas se vc quiser olhar go ahead.

**Comment by tiagofassoni** [comment]
Não, concordo com você. Quatro ifs e é isso aí!

2015-05-21 13:10 GMT-03:00 Leonardo Santagada notifications@github.com:

**Comment by wwared** [comment]
Estamos passando a bounding box direto para o nominatim (usando os parametros viewbox e bounded=1), e ele faz a filtragem pra gente.

Uma coisa que (acho que) é nova da API do nominatim é o addressdetails=[0|1], que passa o endereço separado em componentes (que nem o opencage fazia), e aí a gente tá usando isso pra verificar se a cidade é "São Paulo" e montar o endereço pra mostrar pro usuário. A princípio não precisaria mais da bounding box, mas como não sabemos se o addressdetails funciona bem para todos os endereços, deixamos no código mesmo.

**Comment by tiagofassoni** [comment]
Maravilha, valeu!
