### ISSUE TITLE
Ícones melhores para os POIs

### ISSUE THREAD

**Issue by tiagofassoni** [biciguia/biciguia-frontend#8]
POI = Point of Interest (é a nomenclatura para os pontos de interesse que aparecem no mapa, como as bibliotecas)

Todos os POI aparecem com o mesmo ícone azul. So far, so good. O problema é que fica difícil entender o que é cada coisa na multidão de ícones.

Vejo três jeitos de fazer isso:

1) Pedir para nossa designer fazer os ícones. Seria mais legal, mas demora, a coitada tá se ferrando para fazer o TCC.

2) Fazer os ícones nós mesmos, usando o Maki, um conjunto de ícones do Mapbox, que renderizam facim em leaflet.
https://www.mapbox.com/maki/

3) Partir para a API do Mapbox direto e fazer que nem nesses guias:
https://www.mapbox.com/mapbox.js/example/v1.0.0/single-marker/
https://www.mapbox.com/guides/an-open-platform/#simplestyle

O jeito que vocês preferirem tá ótimo.

**Comment by tiagofassoni** [comment]
Gente, não é só usar os ícones, eles precisam ficar dentro de um marcador (como esse na frontpage do leaflet: http://leafletjs.com/)

Senão, fica difícil enxergá-los no mapa. 

(Outra coisa: genial o ícone de AMA ser um coraçãozinho)

**Comment by vonpupp** [comment]
Done!
